export const STRINGS = {
  projectTitle: 'Want To Do (1TODO)',
  title: '제목',
  desc: '상세 설명',
  nameColon: '제목: ',
  descColon: '상세 설명: ',
  submit: '제출하기',
  tag: '태그',
  tagPlaceholder: '태그 ( , 표시로 구분해주세요)',
  viewAll: '전체 보기',
  viewWIP: '진행중',
  vieCompleted: '완료',
  deleteCompleted: '완료 항목 삭제',
  ddd: '마감 목표일: ',
  edit: '수정',
  delete: '삭제',
  close: '닫기',
  titleNecessary: '제목은 필수 입력 요소입니다',
  titleNeed10: '제목은 최대 10글자입니다',
  confirmExit: '저장되지 않았습니다. 정말 나가시겠습니까?'
}